---
name: Build Suite
on:
  workflow_call:
    inputs:
      distribution:
        description: 'Distribution name, e.g. debian.'
        type: string
        required: true
      codename:
        description: 'Debian codename.'
        type: string
        required: true
      suite:
        description: 'Debian suite.'
        type: string
        required: true
      active:
        description: 'Use default/archive apt mirror.'
        type: boolean
        required: true
      architectures:
        description: 'Architectures in JSON array'
        type: string
        required: true
      repository:
        description: 'Target docker repository'
        type: string
        required: true
      dry_run:
        description: 'Do not push to registry'
        type: boolean
        default: true
    secrets:
      username:
        required: false
      password:
        required: false

permissions:
  contents: read
  packages: write

env:
  DEBUERREOTYPE_IMAGE: ghcr.io/vicamo/debuerreotype:0.18-dev-20260711
  DISTRO: ${{ inputs.distribution }}
  CODENAME: ${{ inputs.codename }}
  SUITE: ${{ inputs.suite }}
  ACTIVE: ${{ inputs.active && 'true' || '' }}
  REPOSITORY: ${{ inputs.repository }}
  DRY_RUN: ${{ inputs.dry_run && 'true' || '' }}

jobs:
  per-arch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJSON(inputs.architectures) }}
    env:
      ARCH: ${{ matrix.arch }}
      PLATFORM: ${{ matrix.platform }}
      USE_PORTS: ${{ matrix.use_ports && 'true' || 'false' }}
      KNOWN_FAILURE: ${{ matrix.known_failure }}
      # Use the snapshot from yesterday to prevent under sync.
      SNAPSHOT_DATE: ${{ matrix.timestamp || 'yesterday' }}
      INCLUDE_PKGS: ${{ matrix.pkgs }}
    steps:
      - name: Set up QEMU (docker/setup-qemu-action)
        if: matrix.qemu == '' && matrix.arch != 'amd64' && matrix.arch != 'i386'
        uses: docker/setup-qemu-action@v4

      - name: Set up QEMU (Ubuntu)
        if: matrix.qemu != '' && matrix.arch != 'amd64' && matrix.arch != 'i386'
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq binfmt-support qemu-user-static

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: v0.12.0

      - name: Dump QEMU supportness
        run: ls -al /proc/sys/fs/binfmt_misc

      - name: Pull debuerreotype image
        run: docker pull "${DEBUERREOTYPE_IMAGE}"

      - name: Debuerreotype
        id: debuerreotype
        continue-on-error: ${{ matrix.known_failure != '' }}
        timeout-minutes: 20
        run: |
          epoch="$(TZ=UTC date --date "${SNAPSHOT_DATE}" +%s)"
          serial="$(TZ=UTC date --date "@$epoch" +%Y%m%d)"

          mkdir -p debuerreotype/output
          output_dir="output/${serial}/${ARCH}/${CODENAME}"

          args=()
          [ -n "${ACTIVE}" ] && [ -z "${{ matrix.timestamp }}" ] || args+=('--eol')
          [ "${USE_PORTS}" == 'false' ] || args+=('--ports')
          [ -z "${INCLUDE_PKGS}" ] || args+=(--include "${INCLUDE_PKGS}")
          args+=(--arch "${ARCH}")

          ret=0
          # Allow building debian experimental (symlink not in image)
          docker run --rm --init \
              --hostname debuerreotype \
              --cap-add SYS_ADMIN --cap-drop SETFCAP \
              --security-opt apparmor=unconfined \
              --security-opt seccomp=unconfined \
              --tmpfs /tmp:dev,exec,suid,noatime \
              --env TMPDIR=/tmp --env http_proxy \
              --mount "type=bind,src=$PWD/debuerreotype/output,dst=/output" \
              "${DEBUERREOTYPE_IMAGE}" \
              bash -ec 'ln -sf sid /usr/share/debootstrap/scripts/experimental; exec "$@"' \
              -- "/opt/debuerreotype/examples/${DISTRO}.sh" "${args[@]}" /output "${CODENAME}" "@${epoch}" || ret=$?
          if [[ ${ret} -eq 0 ]]; then
            if [ -n "${KNOWN_FAILURE}" ]; then
              echo "::error title=Expected failure succeeds::Expect ${DISTRO}/${CODENAME}:${ARCH} to fail but passed. See ${KNOWN_FAILURE}"
            fi
          else
            if [ -n "${KNOWN_FAILURE}" ]; then
              echo "::warning title=Expected failure::Expect ${DISTRO}/${CODENAME}:${ARCH} to fail. See ${KNOWN_FAILURE}"
            else
              echo "::error title=Unexpected failure::${DISTRO}/${CODENAME}:${ARCH} failed with ${ret}"
            fi
            exit ${ret}
          fi

          echo "output_dir=debuerreotype/${output_dir}" | tee -a "${GITHUB_OUTPUT}"

      - name: Load and test image
        if: ${{ steps.debuerreotype.outcome == 'success' }}
        run: |
          tag="${REPOSITORY}:${CODENAME}-${ARCH}"
          printf "FROM scratch\nADD rootfs.tar.xz /\nCMD [\"/bin/bash\"]" | \
              docker buildx build --load --platform "${PLATFORM}" \
                  --tag "${tag}" \
                  --file - "${{ steps.debuerreotype.outputs.output_dir}}"
          docker run --rm "${tag}" apt-get update

      - uses: actions/upload-artifact@v7
        if: ${{ steps.debuerreotype.outcome == 'success' }}
        with:
          name: ${{ env.CODENAME }}-${{ env.ARCH }}-rootfs
          path: ${{ steps.debuerreotype.outputs.output_dir}}
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - per-arch
    env:
      ARCHES: ${{ inputs.architectures }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.CODENAME }}-*

      - # Add support for more platforms with QEMU (optional)
        name: Set up QEMU
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq binfmt-support qemu-user-static
          ls -al /proc/sys/fs/binfmt_misc

      - id: platforms
        run: |
          platforms="$(echo "${ARCHES}" | jq -c -M 'map(.platform) | join(",")')"
          echo "platforms=${platforms}" | tee -a "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          platforms: ${{ steps.platforms.outputs.platforms }}

      - name: Login to GHCR
        if: ${{ !inputs.dry_run }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.repository }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build images
        run: |
          args=()
          [ -z "${SUITE}" ] || args+=(--suite "${SUITE}")
          [ -z "${DRY_RUN}" ] || args+=(--dry-run)
          [ -n "${DRY_RUN}" ] || args+=(--push)
          while read -r arch known_failure; do
            args+=(--arch "${arch}${known_failure:+:${known_failure}}")
          done < <(echo "${ARCHES}" | \
              jq -r -c -M '.[] | .arch + " " + .known_failure')

          scripts/merge-rootfs "${args[@]}" "${REPOSITORY}" "${CODENAME}"
